# Generated by Django 4.2.1 on 2023-07-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contact_first_name_remove_contact_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Dirección Web')),
            ],
        ),
    ]
