# Generated by Django 4.2.1 on 2023-07-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='web',
            field=models.CharField(default='web', max_length=30),
        ),
    ]
